parameters:
#    ia_cms.example.class: IA\Bundle\CmsBundle\Example

services:
#    ia_cms.example:
#        class: %ia_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
