<?php

namespace IA\Bundle\ServerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPhonesRepository extends EntityRepository
{
	
}
