<?php

namespace IA\Bundle\CmsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
    public function countTotal() 
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(p) FROM IACmsBundle:Page p');

        return $query->getSingleScalarResult();
    }
}
