parameters:
#    ia_aws_test.example.class: IA\Bundle\AwsTestBundle\Example

services:
#    ia_aws_test.example:
#        class: %ia_aws_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
