imports:
    - { resource: parameters.yml }
    - { resource: security.yml }  

# Amazon Web Services Configuration
the_phalcons_amazon_web_services:
    # for stream wrapper use : [S3, SES ...]
    enable_extensions:              []
    credentials:
        key:                        'AKIAIWFF3YTM2F2MTZTA'
        secret:                     '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'
    shared_config:
        region:                     %aws_region%
        version:                    %aws_version%
        account_id:                 %aws_account_id%
        canonical_id:               %aws_canonical_id%
        canonical_name:             %aws_canonical_name%
        mfa_serial:                 %aws_mfa_serial%
        cloudfront_keypair:         %aws_cloudfront_keypair%
        cloudfront_pem:             %aws_cloudfront_pem%
        default_cache_config:       null
        certificate_authority:      false
        disable_auto_config:        false


#server_grove_translation_editor:
#  storage:
#    type: server_grove_translation_editor.storage.orm
#    manager: doctrine.orm.entity_manager
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: IA\Bundle\UsersBundle\Entity\User
            
# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    filters:
        # rewrite CSS
        cssrewrite: ~
        uglifycss:
            # sudo npm install -g uglifycss
            bin: /usr/bin/uglifycss
        uglifyjs2:
            # sudo npm install -g uglify-js
            bin: /usr/bin/uglifyjs
    

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    assets: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            dynamic:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   'empty_database'
                charset:  UTF8
                wrapper_class: 'IA\Bundle\DoctrineBundle\Connection\ConnectionWrapper'
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
                
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
