ia_angular_application:
    resource: "@IAAngularApplicationBundle/Resources/config/routing.yml"
    prefix:   /

ia_cms:
    resource: "@IACmsBundle/Resources/config/routing.yml"
    prefix:   /

IAServerBundle:
    resource: "@IAServerBundle/Resources/config/routing.yml"
    prefix:   /
