parameters:
#    ia_navigation.example.class: IA\Bundle\NavigationBundle\Example

services:
#    ia_navigation.example:
#        class: %ia_navigation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
