<?php

namespace IA\Bundle\MultiLanguageBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends EntityRepository
{
    
}
