
require_js_src: '/bundles/iaangularapplication/vendor/requirejs/require.js'
#base_url: js
base_dir: /

paths:
    # Vendor Paths
    'angular/angular':        
        location: '/bundles/iaangularapplication/vendor/angular/angular.min'
        external: true
    'angular/route':          
        location: '//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular-route'
        external: true

    # Application Paths
    'ia/application':
        location: '/bundles/iaangularapplication/application/application'
        external: true
    'ia/services/Base':
        location: '/bundles/iaangularapplication/application/services/BaseService'
        external: true

shim:
    'angular/route':
        deps: ['angular/angular']
    'angular/angular':
        deps: ['jquery/jquery']
    'ia/application': 
        deps: [ 'jquery/jquery', 'angular/angular', 'angular/route', 'angular/ui/tinymce' ]
        exports: app
    
