
routes:
    contacts:
        name: /contacts
        controller: ContactsController
        templateUrl: /bundles/iaangularapplication/application/templates/contacts.html
        isFree: true
    addContact:
        name: /add-contact
        controller: ContactEditController
        templateUrl: /bundles/iaangularapplication/application/templates/editContact.html
        isFree: true
    editContact:
        name: /edit-contact/:contactId
        controller: ContactEditController
        templateUrl: /bundles/iaangularapplication/application/templates/editContact.html
        isFree: true

default: /contacts