base_dir: /

paths:
    # Vendor Paths
    'jquery/jquery':
        location: '/bundles/iaangularadminpanel/vendor/jquery/dist/jquery.min'
        external: true
    'angular/ui/tinymce':     
        location: '/bundles/iaangularadminpanel/vendor/angular-ui-tinymce/src/tinymce'
        external: true
    'tinyMCE':                
        location: '/bundles/iaangularadminpanel/vendor/tinymce/tinymce.min'
        external: true

    # Application Paths
    'ia/controllers/Contacts':
        location: '/bundles/iaangularadminpanel/js/Controller/ContactsController'
        external: true
    'ia/controllers/EditContact':
        location: '/bundles/iaangularadminpanel/js/Controller/EditContactController'
        external: true
    'ia/services/Contacts':
        location: '/bundles/iaangularadminpanel/js/Service/ContactsService'
        external: true

shim:
  
    'angular/ui/tinymce':
        deps: [ 'angular/angular', 'tinyMCE' ]
    
    
