parameters:
#    ia_users.example.class: IA\Bundle\UsersBundle\Example

services:
#    ia_users.example:
#        class: %ia_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
