<?php

namespace IA\Bundle\WebContentThiefBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{
    public function countTotal() 
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(p) FROM IAWebContentThiefBundle:Project p');

        return $query->getSingleScalarResult();
    }
}

