parameters:
#    ia_multi_language.example.class: IA\Bundle\MultiLanguageBundle\Example

services:
#    ia_multi_language.example:
#        class: %ia_multi_language.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
