
# Fieldsets Controller
ia_web_content_thief_fieldsets_add_field:
    path:     /fieldsets/add-field
    defaults: { _controller: IAWebContentThiefBundle:Fieldsets:addField}
ia_web_content_thief_fieldsets_list:
    path:     /fieldsets
    defaults: { _controller: IAWebContentThiefBundle:Fieldsets:list }
ia_web_content_thief_fieldsets_edit:
    path:     /fieldsets/edit/{id}
    defaults: { _controller: IAWebContentThiefBundle:Fieldsets:edit }
    
# Projects Controller
ia_web_content_thief_list_projects:
    path:     /
    defaults: { _controller: IAWebContentThiefBundle:Projects:listProjects }
ia_web_content_thief_edit_project:
    path:     /edit/{id}
    defaults: { _controller: IAWebContentThiefBundle:Projects:editProject }
ia_web_content_thief_delete_project:
    path:     /delete/{id}
    defaults: { _controller: IAWebContentThiefBundle:Projects:deleteProject }
ia_web_content_thief_preview_project:
    path:     /preview/{id}
    defaults: { _controller: IAWebContentThiefBundle:Projects:previewProject }
ia_web_content_thief_run_project:
    path:     /run/{id}
    defaults: { _controller: IAWebContentThiefBundle:Projects:runProject }
ia_web_content_thief_copy_project:
    path:     /copy/{id}
    defaults: { _controller: IAWebContentThiefBundle:Projects:copyProject }
ia_web_content_thief_browse:
    path:     /browse/{url}
    defaults: { _controller: IAWebContentThiefBundle:Projects:browse }
ia_web_content_projects_add_fields:
    path:     /projects/add-fields
    defaults: { _controller: IAWebContentThiefBundle:Projects:addFields }

# Mappers Controller
ia_web_content_thief_mappers_list:
    path:     /mappers
    defaults: { _controller: IAWebContentThiefBundle:Mappers:list }
ia_web_content_thief_mappers_edit:
    path:     /mappers/edit/{id}
    defaults: { _controller: IAWebContentThiefBundle:Mappers:edit }

# Connections Controller
ia_web_content_thief_connections_list:
    path:     /connections
    defaults: { _controller: IAWebContentThiefBundle:Connections:list }
ia_web_content_thief_connections_edit:
    path:     /connections/edit/{id}
    defaults: { _controller: IAWebContentThiefBundle:Connections:edit }
    
