ia_cms_pages:
    path:     /pages
    defaults: { _controller: IACmsBundle:ServicePages:index }

ia_cms_pages_detail:
    path:     /pages/{id}
    defaults: { _controller: IACmsBundle:ServicePages:detail}

ia_server_delete:
    path:     /pages/delete/{id}
    defaults: { _controller: IACmsBundle:ServicePages:delete }

ia_server_save:
    path:     /pages/save
    defaults: { _controller: IACmsBundle:ServicePages:save }
    requirements:
        _method:  POST

