ia_cms_pages:
    path:     /service/pages
    defaults: { _controller: IACmsBundle:ServicePages:index }

ia_cms_pages_detail:
    path:     /service/pages/detail/{id}
    defaults: { _controller: IACmsBundle:ServicePages:detail}

ia_cms_pages_delete:
    path:     /service/pages/delete/{id}
    defaults: { _controller: IACmsBundle:ServicePages:delete }

ia_cms_pages_save:
    path:     /service/pages/save
    defaults: { _controller: IACmsBundle:ServicePages:save }
    requirements:
        _method:  POST

